name: convertapitos-dev
services:
  server:
    container_name: server_dev
    build:
      context: .
      dockerfile: Dockerfile.dev
    environment:
      NODE_ENV: development
    ports:
      - "${APP_PORT}:${APP_PORT}"
    env_file:
      - .env.development
    volumes:
      - .:/usr/src/app
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - app-network
    command: ["npm", "run", "start:dev"]

  postgres:
    image: postgres:latest
    container_name: postgres_dev
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    env_file:
      - .env.development
    ports:
      - "5432:5432"
    volumes:
      - postgres-dev-data:/var/lib/postgresql/data
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s

volumes:
  postgres-dev-data:
    driver: local

networks:
  app-network:
    driver: bridge