name: convertapitos-dev
services:
  server:
    container_name: convertapitos_dev
    build:
      context: .
      dockerfile: Dockerfile.dev
    environment:
      NODE_ENV: development
    ports:
      - "${PORT}:${PORT}"
    env_file:
      - .env.development
    volumes:
      - .:/usr/src/app
    depends_on:
      - postgres
    networks:
      - app-network

  postgres:
    image: postgres:latest
    container_name: postgres_dev
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    env_file:
      - .env.development
    ports:
      - "5433:5432"
    volumes:
      - postgres-dev-data:/var/lib/postgresql/data
    networks:
      - app-network

volumes:
  postgres-dev-data:
    driver: local

networks:
  app-network:
    driver: bridge